export const SET_LOCATION_WEATHER = 'SET_LOCATION_WEATHER'
export const SET_LOCATION_WEATHER_ERROR = 'SET_LOCATION_WEATHER_ERROR'
export const SET_LOCATION_WEATHER_LOADING = 'SET_LOCATION_WEATHER_LOADING'

export const SET_CITY_WEATHER = 'SET_CITY_WEATHER'
export const SET_CITY_WEATHER_LOADING = 'SET_CITY_WEATHER_LOADIN'
export const SET_CITY_WEATHER_ERROR = 'SET_CITY_WEATHER_ERROR'

export const SET_SEARCH_CITY = 'SET_SEARCH_CITY'

export const SET_GEO = 'SET_GEO'
